name: Indeed Engineering Open Source
# http://stackoverflow.com/questions/10759577/underscore-issues-jekyll-redcarpet-github-flavored-markdown
markdown: redcarpet
highlighter: pygments
# jekyll serve --watch --baseurl=
# permalinks are relative to their parent folder
relative_permalinks: false
redcarpet:
  extensions: ["fenced_code_blocks", "no_intra_emphasis", "autolink", "tables", "with_toc_data"]

  exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile.rb', 'README.md']
